sudo: false

language: php

php:
    - 7.0
    - 7.1
    - 7.2
    - nightly

services:
  - mysql

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    #Launch the php server and phantomJs server
    - php -S 127.0.0.1:8888 -t ./.. >/dev/null 2>&1 &
    - phantomjs --webdriver=4444 >/dev/null 2>&1 &
    
    - chmod 777 log
    - composer self-update

install:
    #Update dependencies
    - composer install --no-interaction --prefer-dist
    - composer require codeception/codeception
    

script:
    - cp ./.robo_config ~/
    - ./vendor/bin/robo tests:install --env="travis"
    
    #Verify php coding standart
    - ./vendor/bin/phpcs . -p --standard=./phpcs.xml

    #Test installation of the website
    - ./vendor/bin/robo install
    - ./vendor/bin/robo wp:init --env="test"
    
    #Acceptance test by Codeception
    - ./vendor/bin/codecept run --debug